CREATE TABLE EMPREGADO (
    NOME VARCHAR2(50),
    RG VARCHAR2(10) PRIMARY KEY,
    CIC VARCHAR2(10),
    DEPTO NUMBER,
    RG_SUPERVISOR VARCHAR2(10),
    SALARIO NUMBER
)

CREATE TABLE DEPARTAMENTO (
    NOME VARCHAR(30),
    NUMERO NUMBER PRIMARY KEY,
    RG_GERENTE VARCHAR2(10)
)

CREATE TABLE PROJETO (
    NOME VARCHAR(30),
    NUMERO NUMBER PRIMARY KEY,
    LOCALIZACAO VARCHAR2(50)
)

CREATE TABLE DEPENDENTES (
    RG_RESPONSAVEL VARCHAR(10),
    NOME_DEPENDENTE VARCHAR(30),
    NASCIMENTO DATE,
    RELACAO VARCHAR(20),
    SEXO VARCHAR(15),
    PRIMARY KEY (RG_RESPONSAVEL, NOME_DEPENDENTE)
)

CREATE TABLE DEPARTAMENTO_PROJETO (
    NUMERO_DEPTO NUMBER,
    NUMERO_PROJETO NUMBER,
    PRIMARY KEY (NUMERO_DEPTO, NUMERO_PROJETO)
)

CREATE TABLE EMPREGADO_PROJETO (
   RG_EMPREGADO VARCHAR(10),
   NUMERO_PROJETO NUMBER,
   HORAS NUMBER,
   PRIMARY KEY (RG_EMPREGADO, NUMERO_PROJETO)
)

ALTER TABLE EMPREGADO ADD CONSTRAINT FK_EMPREGADO_DEPARTAMENTO FOREIGN KEY (DEPTO) REFERENCES DEPARTAMENTO (NUMERO)
ALTER TABLE EMPREGADO ADD CONSTRAINT FK_EMPREGADO_SUPERVISOR FOREIGN KEY (RG_SUPERVISOR) REFERENCES EMPREGADO (RG)
ALTER TABLE DEPARTAMENTO ADD CONSTRAINT FK_DEPARTAMENTO_GERENTE FOREIGN KEY (RG_GERENTE) REFERENCES EMPREGADO (RG)
ALTER TABLE DEPENDENTES ADD CONSTRAINT FK_DEPENDENTES_RESPONSAVEL FOREIGN KEY (RG_RESPONSAVEL) REFERENCES EMPREGADO (RG)
ALTER TABLE DEPARTAMENTO_PROJETO ADD CONSTRAINT FK_DEPARTAMENTO_PROJETO_NUMERO_DEPARTAMENTO FOREIGN KEY (NUMERO_DEPTO) REFERENCES DEPARTAMENTO (NUMERO)
ALTER TABLE DEPARTAMENTO_PROJETO ADD CONSTRAINT FK_DEPARTAMENTO_PROJETO_NUMERO_PROJETO FOREIGN KEY (NUMERO_PROJETO) REFERENCES PROJETO (NUMERO)
ALTER TABLE EMPREGADO_PROJETO ADD CONSTRAINT FK_EMPREGADO_PROJETO_RG_EMPREGADO FOREIGN KEY (RG_EMPREGADO) REFERENCES EMPREGADO (RG)
ALTER TABLE EMPREGADO_PROJETO ADD CONSTRAINT FK_EMPREGADO_PROJETO_NUMERO_PROJETO FOREIGN KEY (NUMERO_PROJETO) REFERENCES PROJETO (NUMERO)

INSERT INTO PROJETO VALUES ('Financeiro 1', 5, 'São Paulo');
INSERT INTO PROJETO VALUES ('Motor 3', 10, 'Rio Claro');
INSERT INTO PROJETO VALUES ('Prédio Central', 20, 'Campinas');

INSERT INTO EMPREGADO (NOME, RG, CIC, DEPTO, RG_SUPERVISOR, SALARIO) VALUES ('João Luiz', '10101010', '11111111', 1, NULL, 3000);
INSERT INTO EMPREGADO (NOME, RG, CIC, DEPTO, RG_SUPERVISOR, SALARIO) VALUES ('Fernando', '20202020', '22222222', 2, '10101010', 2500);
INSERT INTO EMPREGADO (NOME, RG, CIC, DEPTO, RG_SUPERVISOR, SALARIO) VALUES ('Ricardo', '30303030', '33333333', 2, '10101010', 2300);
INSERT INTO EMPREGADO (NOME, RG, CIC, DEPTO, RG_SUPERVISOR, SALARIO) VALUES ('Jorge', '40404040', '44444444', 2, '20202020', 4200);
INSERT INTO EMPREGADO (NOME, RG, CIC, DEPTO, RG_SUPERVISOR, SALARIO) VALUES ('Renato', '50505050', '55555555', 3, '20202020', 1300);

INSERT INTO DEPARTAMENTO (NOME, NUMERO, RG_GERENTE) VALUES ('Contabilidade', 1, '10101010');
INSERT INTO DEPARTAMENTO (NOME, NUMERO, RG_GERENTE) VALUES ('Engenharia Civil', 2, '30303030');
INSERT INTO DEPARTAMENTO (NOME, NUMERO, RG_GERENTE) VALUES ('Engenharia Mecânica', 3, '20202020');

INSERT INTO DEPENDENTES (RG_RESPONSAVEL, NOME_DEPENDENTE, NASCIMENTO, RELACAO, SEXO) VALUES ('10101010', 'Jorge', TO_DATE('27/12/86', 'DD/MM/YY'), 'Filho', 'Masculino')
INSERT INTO DEPENDENTES (RG_RESPONSAVEL, NOME_DEPENDENTE, NASCIMENTO, RELACAO, SEXO) VALUES ('10101010', 'Luiz', TO_DATE('18/11/79', 'DD/MM/YY'), 'Filho', 'Masculino')
INSERT INTO DEPENDENTES (RG_RESPONSAVEL, NOME_DEPENDENTE, NASCIMENTO, RELACAO, SEXO) VALUES ('20202020', 'Fernanda', TO_DATE('14/02/69', 'DD/MM/YY'), 'Conjuge', 'Feminino')
INSERT INTO DEPENDENTES (RG_RESPONSAVEL, NOME_DEPENDENTE, NASCIMENTO, RELACAO, SEXO) VALUES ('20202020', 'Angelo', TO_DATE('10/02/95', 'DD/MM/YY'), 'Filho', 'Masculino')
INSERT INTO DEPENDENTES (RG_RESPONSAVEL, NOME_DEPENDENTE, NASCIMENTO, RELACAO, SEXO) VALUES ('30303030', 'Adreia', TO_DATE('01/05/90', 'DD/MM/YY'), 'Filho', 'Feminino')

INSERT INTO DEPARTAMENTO_PROJETO (NUMERO_DEPTO, NUMERO_PROJETO) VALUES (2, 5)
INSERT INTO DEPARTAMENTO_PROJETO (NUMERO_DEPTO, NUMERO_PROJETO) VALUES (3, 10)
INSERT INTO DEPARTAMENTO_PROJETO (NUMERO_DEPTO, NUMERO_PROJETO) VALUES (2, 20)

INSERT INTO EMPREGADO_PROJETO (RG_EMPREGADO, NUMERO_PROJETO, HORAS) VALUES ('20202020', 5, 10);
INSERT INTO EMPREGADO_PROJETO (RG_EMPREGADO, NUMERO_PROJETO, HORAS) VALUES ('20202020', 10, 25);
INSERT INTO EMPREGADO_PROJETO (RG_EMPREGADO, NUMERO_PROJETO, HORAS) VALUES ('30303030', 5, 35);
INSERT INTO EMPREGADO_PROJETO (RG_EMPREGADO, NUMERO_PROJETO, HORAS) VALUES ('40404040', 20, 50)
INSERT INTO EMPREGADO_PROJETO (RG_EMPREGADO, NUMERO_PROJETO, HORAS) VALUES ('50505050', 20, 35)